Dialog-fu
==============
Chris Riddoch <riddochc@gmail.com>
0.1, 2011-08-22

== DESCRIPTION ==

This library provides a high-level mechanism to asking users for input with
dialog/kdialog/zenity

== FEATURES/PROBLEMS ==

FIXME (list of features or problems)

== SYNOPSIS ==

  d = calendar(:width => 480, :title => "Date entry thingie",
               :text => "Enter some weird date...",
               :initial_date => DateTime.new(2011,1,1))
  puts "Selected date: " + d.to_s

  text_entry(:width => 800, :entry_text => "Foo things")

  info(:debug => true, :text => "Something you should know about...")

  t = file_selection(:filename => ENV['HOME'] + "/", :multiple => true)
  t.each {|f| puts f }

  t = selection_list(["one", "two", "three"])
  puts t.inspect

  t = textbox("Hello, world!\nFine day, isn't it?", :editable => true)
  puts t

  i = range(1..10, :debug => true)
  puts i

== REQUIREMENTS ==

Ruby gems: escape
Zenity, for now... others forthcoming

== INSTALL ==

  rake gem:install 

== LICENSE ==

Copyright © 2011 Chris Riddoch

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


